export const profileStrings = {
profileTitle:"Lorem Ipsum",
fullName:"Full Name",
name:"Name",
email:"Email",
Ailment:"Ailment",
ProductDesigner:"Product Designer",
notReq:"(Not Required)",
location:"Location",
notifications:"Notifications",
store:"Store",
phoneNumLabel:"Phone Number",
address:"Address",
website:"Website",
nameisRequired:"Name is required.",
error:"Error!",
emailisRequired:"Email is required.",
emailNotValid:"Email is not valid",
confirmToDeleteAlert:"Are you sure you want to delete profile?",
phoneNumberIsRequired:"Phone number is required.",
addressIsRequired:"Address is required.",
websiteIsRequired:"Website is required.",
}