export const customAlertStrings = {
    whoAreYou:"Who are You?",
    areYouCustomer:"Are you selling a product or a connoisseur?",
    Individual:"Individual",
    Store:"Store",
    individualDescription1:"Explore strains",
    individualDescription2:"Share experiences",
    individualDescription3:"Connect with others",
    storeDescription1:"Register your shop",
    storeDescription2:"Reach a wider audience",
    storeDescription3:"Manage your listings",
    storeDescription4:"Grow your business",
    camera:"Camera",
    gallery:"Gallery",
    chooseFrom:"Choose From",
    loginFirst:"You need to login first.",
    proceedToLogin:'Proceed to Login',
    staylogout:"Stay log out",
    cancel:"Cancel",
    addCard:"Add card to your profile?",
    cardEditText:"(You can edit it there)",
    shareCard:"Share Card",
    hide:"Hide",
    report:"Report"
}